// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class TipoConsultasUpdateDto
    {
        public int tico_Id { get; set; }
        public string tico_Descripcion { get; set; }
        public int? tico_UsuarioModifica { get; set; }
    }
}
