// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class TipoConsultasDetailDto
    {
        public int tico_Id { get; set; }
        public string tico_Descripcion { get; set; }
        public int tico_UsuarioRegistra { get; set; }
        public DateTime tico_FechaRegistra { get; set; }
        public int? tico_UsuarioModifica { get; set; }
        public DateTime? tico_FechaModifica { get; set; }
    }
}
