// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class AlergiasUpdateDto
    {
        public int algi_Id { get; set; }
        public string algi_Nombre { get; set; }
        public string algi_Descripcion { get; set; }
        public int? algi_UsuarioModifica { get; set; }
    }
}
