// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class MedicamentosSelectDto
    {
        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public decimal medi_Precio { get; set; }
        public string medi_Descripcion { get; set; }
    }
}
