// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class Alergias_DetailDto
    {
        public int algi_Id { get; set; }
        public string algi_Nombre { get; set; }
        public string algi_Descripcion { get; set; }
        public int algi_UsuarioRegistra { get; set; }
        public DateTime algi_FechaRegistra { get; set; }
        public int? algi_UsuarioModifica { get; set; }
        public DateTime? algi_FechaModifica { get; set; }
    }
}
