// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class AlergiasDto
    {
        [Key]
        public int algi_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string algi_Nombre { get; set; }
        /// <summary>
        /// Información extra sobre la alergia.
        /// </summary>
        [StringLength(300)]
        public string algi_Descripcion { get; set; }
        public bool algi_EsEliminado { get; set; }
        public int algi_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime algi_FechaRegistra { get; set; }
        public int? algi_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? algi_FechaModifica { get; set; }
    }
}
