// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class CargosDto
    {
        [Key]
        public int carg_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string carg_Descripcion { get; set; }
        public bool carg_EsEliminado { get; set; }
        public int carg_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime carg_FechaRegistra { get; set; }
        public int? carg_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? carg_FechaModifica { get; set; }
    }
}
