// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    /// <summary>
    /// Indica todas las cirugias que estan disponibles para un paciente.
    /// </summary>
    public partial class CirugiasDto
    {
        [Key]
        public int ciru_Id { get; set; }
        [StringLength(250)]
        public string ciru_Descripcion { get; set; }
        public bool ciru_EsEliminado { get; set; }
        public int ciru_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ciru_FechaRegistra { get; set; }
        public int? ciru_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ciru_FechaModifica { get; set; }
    }
}
