// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class Cirugias_DetailDto
    {
        public int ciru_Id { get; set; }
        public string ciru_Descripcion { get; set; }
        public int ciru_UsuarioRegistra { get; set; }
        public DateTime ciru_FechaRegistra { get; set; }
        public int? ciru_UsuarioModifica { get; set; }
        public DateTime? ciru_FechaModifica { get; set; }
    }
}
