// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class CitasDto
    {
        [Key]
        public int cita_Id { get; set; }
        public int paci_Id { get; set; }
        public int empd_Id { get; set; }
        public int tici_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime cita_FechaCita { get; set; }
        public bool cita_EsEliminado { get; set; }
        public int cita_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime cita_FechaRegistra { get; set; }
        public int? cita_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cita_FechaModifica { get; set; }
    }
}
