// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class Citas_SelectDto
    {
        public int cita_Id { get; set; }
        public string paci_Nombre { get; set; }
        public string empd_Nombre { get; set; }
        public string carg_Descripcion { get; set; }
        public string tici_Descripcion { get; set; }
    }
}
