// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class ConsultoriosDto
    {
        [Key]
        public int cons_Id { get; set; }
        /// <summary>
        /// Informacion relevante de la ubicacion del consultorio.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string cons_Descripcion { get; set; }
        public bool cons_EsEliminado { get; set; }
        [Required]
        public int cons_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime cons_FechaRegistra { get; set; }
        public int? cons_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cons_FechaModifica { get; set; }
    }
}
