// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class Consultorios_DetailDto
    {
        public int cons_Id { get; set; }
        public string cons_Descripcion { get; set; }
        public int cons_UsuarioRegistra { get; set; }
        public DateTime cons_FechaRegistra { get; set; }
        public int? cons_UsuarioModifica { get; set; }
        public DateTime? cons_FechaModifica { get; set; }
    }
}
