// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class EmpleadosDto
    {
        public int empd_Id { get; set; }
        public int pers_Id { get; set; }
        public int carg_Id { get; set; }
        public int? cons_Id { get; set; }
        public int jorn_Id { get; set; }
    }
}
