// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class FrecuenciasCardiacasDto
    {
        public int rica_Id { get; set; }
        /// <summary>
        /// Identificador del paciente
        /// </summary>
        public int paci_Id { get; set; }
        /// <summary>
        /// Frecuencia cardíaca del paciente
        /// </summary>
        [StringLength(150)]
        public string rica_Informacion { get; set; }
        public bool rica_EsEliminado { get; set; }
        public int rica_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime rica_FechaRegistra { get; set; }
        public int? rica_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? rica_FechaModifica { get; set; }
    }
}
