// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class JornadasDto
    {
        [Key]
        public int jorn_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string jorn_Descripcion { get; set; }
        public bool jorn_EsEliminado { get; set; }
        public int jorn_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime jorn_FechaRegistra { get; set; }
        public int? jorn_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? jorn_FechaModifica { get; set; }
    }
}
