// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class Medicamentos_UpdateDto
    {
        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public decimal medi_Precio { get; set; }
        public string medi_Descripcion { get; set; }
        public int? medi_UsuarioModifica { get; set; }
    }
}
