// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class MedicamentosDto
    {
        [Key]
        public int medi_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string medi_Nombre { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal medi_Precio { get; set; }
        [StringLength(300)]
        public string medi_Descripcion { get; set; }
        public bool medi_EsEliminado { get; set; }
        public int medi_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime medi_FechaRegistra { get; set; }
        public int? medi_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? medi_FechaModifica { get; set; }
    }
}
