// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class PersonasDto
    {
        /// <summary>
        /// Indica el identificador único de la persona.
        /// </summary>
        [Key]
        public int pers_Id { get; set; }
        /// <summary>
        /// Serie de digitos dado por el registro nacional para distingir únicamente a una persona.
        /// </summary>
        [Required]
        [StringLength(13)]
        public string pers_Identidad { get; set; }
        /// <summary>
        /// Primer nombre de la persona.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string pers_PrimerNombre { get; set; }
        /// <summary>
        /// Segundo nombre de la persona.
        /// </summary>
        [StringLength(50)]
        public string pers_SegundoNombre { get; set; }
        /// <summary>
        /// Primer apellido dado a la persona.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string pers_ApellidoPaterno { get; set; }
        /// <summary>
        /// Segundo apellido de la persona.
        /// </summary>
        [StringLength(50)]
        public string pers_ApellidoMaterno { get; set; }
        /// <summary>
        /// Fecha en la que nacio la persona.
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime pers_FechaNacimiento { get; set; }
        /// <summary>
        /// Medio por el cual permite ponerse en contacto mediante mensaje electronico con la persona.
        /// </summary>
        [StringLength(150)]
        public string pers_CorreoElectronico { get; set; }
        /// <summary>
        /// Almacena una serie de digitos de telefono.
        /// </summary>
        [Required]
        [StringLength(9)]
        public string pers_Telefono { get; set; }
        /// <summary>
        /// Información sobre una direccion aproximada.
        /// </summary>
        [StringLength(150)]
        public string pers_Calle { get; set; }
        /// <summary>
        /// Información sobre una direccion aproximada.
        /// </summary>
        [StringLength(150)]
        public string pers_Ciudad { get; set; }
        /// <summary>
        /// Información sobre una direccion aproximada.
        /// </summary>
        [StringLength(150)]
        public string pers_Provincia { get; set; }
        /// <summary>
        /// Información sobre una direccion aproximada.
        /// </summary>
        [StringLength(150)]
        public string pers_CodigoPostal { get; set; }
        /// <summary>
        /// Información sobre una direccion aproximada.
        /// </summary>
        [StringLength(150)]
        public string pers_Pais { get; set; }
        /// <summary>
        /// Indica el sexo de la persona.
        /// </summary>
        [Required]
        [StringLength(1)]
        public string pers_Sexo { get; set; }
        /// <summary>
        /// Indica el estado actual de la persona.
        /// </summary>
        [Required]
        public bool? pers_EsActivo { get; set; }
        public bool pers_EsEliminado { get; set; }
        public int pers_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime pers_FechaRegistra { get; set; }
        public int? pers_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pers_FechaModifica { get; set; }
    }
}
