// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class PesosDto
    {
        [Key]
        public int peso_Id { get; set; }
        public int paci_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string peso_Descripcion { get; set; }
        public bool peso_EsEliminado { get; set; }
        public int peso_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime peso_FechaRegistra { get; set; }
        public int? peso_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? peso_FechaModifica { get; set; }
    }
}
