// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class Pesos_SelectDto
    {
        public int peso_Id { get; set; }
        public int paci_Id { get; set; }
        public string peso_Descripcion { get; set; }
    }
}
