// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class PrescripcionesDto
    {
        [Key]
        public int pres_Id { get; set; }
        public int cita_Id { get; set; }
        public int medi_Id { get; set; }
        [StringLength(150)]
        public string pres_Descripcion { get; set; }
        public bool pres_EsEliminado { get; set; }
        public int pres_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime pres_FechaRegistra { get; set; }
        public int? pres_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pres_FechaModifica { get; set; }
    }
}
