// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class TiposSangre_UpdateDto
    {
        public int tipsan_Id { get; set; }
        
        public string tipsan_Descripcion { get; set; }
        public int? tipsan_UsuarioModifica { get; set; }
    }
}
