// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class TipoConsultasDto
    {
        [Key]
        public int tico_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string tico_Descripcion { get; set; }
        public bool tico_EsEliminado { get; set; }
        public int tico_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime tico_FechaRegistra { get; set; }
        public int? tico_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? tico_FechaModifica { get; set; }
    }
}
