// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class TipoCitasDto
    {
        [Key]
        public int tici_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string tici_Descripcion { get; set; }
        public bool tici_EsEliminado { get; set; }
        public int tici_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime tici_FechaRegistra { get; set; }
        public int? tici_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? tici_FechaModifica { get; set; }
    }
}
