// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class TiposSangreDto
    {
        [Key]
        public int tipsan_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string tipsan_Descripcion { get; set; }
        public bool tipsan_EsEliminado { get; set; }
        public int tipsan_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime tipsan_FechaRegistra { get; set; }
        public int? tipsan_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? tipsan_FechaModifica { get; set; }
    }
}
