// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using System;
using PROMEDICAL.Entities.Entities;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbAlergiasConfiguration : IEntityTypeConfiguration<tbAlergias>
    {
        public void Configure(EntityTypeBuilder<tbAlergias> entity)
        {
            entity.HasKey(e => e.algi_Id);

            entity.Property(e => e.algi_Descripcion)
                .HasMaxLength(300)
                .HasComment("Información extra sobre la alergia.");

            entity.Property(e => e.algi_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.algi_FechaRegistra).HasColumnType("datetime");

            entity.Property(e => e.algi_Nombre).HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbAlergias> entity);
    }
}
