// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;
using PROMEDICAL.Entities.Entities;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbCargosConfiguration : IEntityTypeConfiguration<tbCargos>
    {
        public void Configure(EntityTypeBuilder<tbCargos> entity)
        {
            entity.HasKey(e => e.carg_Id);

            entity.Property(e => e.carg_Descripcion)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.carg_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.carg_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbCargos> entity);
    }
}
