// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbCitasConfiguration : IEntityTypeConfiguration<tbCitas>
    {
        public void Configure(EntityTypeBuilder<tbCitas> entity)
        {
            entity.HasKey(e => e.cita_Id)
                .HasName("PK_tbCita");

            entity.Property(e => e.cita_FechaCita).HasColumnType("datetime");

            entity.Property(e => e.cita_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.cita_FechaRegistra).HasColumnType("datetime");

            entity.HasOne(d => d.empd)
                .WithMany(p => p.tbCitas)
                .HasForeignKey(d => d.empd_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.paci)
                .WithMany(p => p.tbCitas)
                .HasForeignKey(d => d.paci_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbCita_tbPaciente_paci_Id");

            entity.HasOne(d => d.tici)
                .WithMany(p => p.tbCitas)
                .HasForeignKey(d => d.tici_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbCita_tbTipoCita_tici_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbCitas> entity);
    }
}
