// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbCirugiasConfiguration : IEntityTypeConfiguration<tbCirugias>
    {
        public void Configure(EntityTypeBuilder<tbCirugias> entity)
        {
            entity.HasKey(e => e.ciru_Id)
                .HasName("PK_tbCirugia");

            entity.HasComment("Indica todas las cirugias que estan disponibles para un paciente.");

            entity.Property(e => e.ciru_Descripcion).HasMaxLength(250);

            entity.Property(e => e.ciru_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.ciru_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbCirugias> entity);
    }
}
