// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbConsultoriosConfiguration : IEntityTypeConfiguration<tbConsultorios>
    {
        public void Configure(EntityTypeBuilder<tbConsultorios> entity)
        {
            entity.HasKey(e => e.cons_Id);

            entity.Property(e => e.cons_Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Informacion relevante de la ubicacion del consultorio.");

            entity.Property(e => e.cons_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.cons_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbConsultorios> entity);
    }
}
