// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbEmpleadosConfiguration : IEntityTypeConfiguration<tbEmpleados>
    {
        public void Configure(EntityTypeBuilder<tbEmpleados> entity)
        {
            entity.HasKey(e => e.empd_Id);

            entity.Property(e => e.empd_Id).ValueGeneratedNever();

            entity.Property(e => e.empd_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.empd_FechaRegistra).HasColumnType("datetime");

            entity.HasOne(d => d.carg)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.carg_Id);

            entity.HasOne(d => d.cons)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.cons_Id);

            entity.HasOne(d => d.emps)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.emps_Id);

            entity.HasOne(d => d.espc)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.espc_Id);

            entity.HasOne(d => d.jorn)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.jorn_Id);

            entity.HasOne(d => d.pers)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.pers_Id);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEmpleados> entity);
    }
}
