// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbEspecialidadesConfiguration : IEntityTypeConfiguration<tbEspecialidades>
    {
        public void Configure(EntityTypeBuilder<tbEspecialidades> entity)
        {
            entity.HasKey(e => e.espc_Id);

            entity.Property(e => e.espc_Descripcion).HasMaxLength(150);

            entity.Property(e => e.espc_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.espc_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEspecialidades> entity);
    }
}
