// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbFrecuenciasCardiacasConfiguration : IEntityTypeConfiguration<tbFrecuenciasCardiacas>
    {
        public void Configure(EntityTypeBuilder<tbFrecuenciasCardiacas> entity)
        {
            entity.HasKey(e => e.rica_Id)
                .HasName("PK_tbFrecuenciaCardiaca");

            entity.Property(e => e.rica_Id).ValueGeneratedNever();

            entity.Property(e => e.paci_Id).HasComment("Identificador del paciente");

            entity.Property(e => e.rica_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.rica_FechaRegistra).HasColumnType("datetime");

            
            entity.HasOne(d => d.paci)
                .WithMany(p => p.tbFrecuenciasCardiacas)
                .HasForeignKey(d => d.paci_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbFrecuenciaCardiaca_tbPaciente_paci_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbFrecuenciasCardiacas> entity);
    }
}
