// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbJornadasConfiguration : IEntityTypeConfiguration<tbJornadas>
    {
        public void Configure(EntityTypeBuilder<tbJornadas> entity)
        {
            entity.HasKey(e => e.jorn_Id);

            entity.Property(e => e.jorn_Descripcion).HasMaxLength(150);

            entity.Property(e => e.jorn_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.jorn_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbJornadas> entity);
    }
}
