// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbMedicamentosConfiguration : IEntityTypeConfiguration<tbMedicamentos>
    {
        public void Configure(EntityTypeBuilder<tbMedicamentos> entity)
        {
            entity.HasKey(e => e.medi_Id);

            entity.Property(e => e.medi_Descripcion).HasMaxLength(300);

            entity.Property(e => e.medi_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.medi_FechaRegistra).HasColumnType("datetime");

            entity.Property(e => e.medi_Marca).HasMaxLength(150);

            entity.Property(e => e.medi_Nombre).HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbMedicamentos> entity);
    }
}
