// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbPacientes_tbAlergiasConfiguration : IEntityTypeConfiguration<tbPacientes_tbAlergias>
    {
        public void Configure(EntityTypeBuilder<tbPacientes_tbAlergias> entity)
        {
            entity.HasKey(e => e.paal_Id);

            entity.HasOne(d => d.algi)
                .WithMany(p => p.tbPacientes_tbAlergias)
                .HasForeignKey(d => d.algi_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbPacientes_tbAlergias_algi_Id");

            entity.HasOne(d => d.paci)
                .WithMany(p => p.tbPacientes_tbAlergias)
                .HasForeignKey(d => d.paci_Id)
                .HasConstraintName("FK_tbPacientes_tbAlergias_paci_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPacientes_tbAlergias> entity);
    }
}
