// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbPacientesConfiguration : IEntityTypeConfiguration<tbPacientes>
    {
        public void Configure(EntityTypeBuilder<tbPacientes> entity)
        {
            entity.HasKey(e => e.paci_Id)
                .HasName("PK_tbPaciente");

            entity.Property(e => e.paci_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.paci_FechaRegistra).HasColumnType("datetime");

            entity.Property(e => e.tipoSangre)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.HasOne(d => d.pers)
                .WithMany(p => p.tbPacientes)
                .HasForeignKey(d => d.pers_Id)
                .HasConstraintName("FK_tbPaciente_tbPersonas_pers_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPacientes> entity);
    }
}
