// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbPacientes_tbCirugiasConfiguration : IEntityTypeConfiguration<tbPacientes_tbCirugias>
    {
        public void Configure(EntityTypeBuilder<tbPacientes_tbCirugias> entity)
        {
            entity.HasKey(e => e.pagi_Id);

            entity.Property(e => e.pagi_Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.paci)
                .WithMany(p => p.tbPacientes_tbCirugias)
                .HasForeignKey(d => d.paci_Id)
                .HasConstraintName("FK_tbPacientes_tbCirugias_paci_Id");

            entity.HasOne(d => d.pagi)
                .WithOne(p => p.tbPacientes_tbCirugias)
                .HasForeignKey<tbPacientes_tbCirugias>(d => d.pagi_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbPacientes_tbCirugias_ciru_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPacientes_tbCirugias> entity);
    }
}
