// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbPesosConfiguration : IEntityTypeConfiguration<tbPesos>
    {
        public void Configure(EntityTypeBuilder<tbPesos> entity)
        {
            entity.HasKey(e => e.peso_Id);

            entity.Property(e => e.peso_Descripcion)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.peso_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.peso_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPesos> entity);
    }
}
