// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbPesosConfiguration : IEntityTypeConfiguration<tbPesos>
    {
        public void Configure(EntityTypeBuilder<tbPesos> entity)
        {
            entity.HasKey(e => e.peso_Id);

            entity.Property(e => e.peso_Descripcion).HasMaxLength(150);

            entity.Property(e => e.peso_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.peso_FechaRegistra).HasColumnType("datetime");

            entity.HasOne(d => d.paci)
                .WithMany(p => p.tbPesos)
                .HasForeignKey(d => d.paci_Id)
                .HasConstraintName("FK_tbPesos_tbPaciente_paci_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPesos> entity);
    }
}
