// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbPersonasConfiguration : IEntityTypeConfiguration<tbPersonas>
    {
        public void Configure(EntityTypeBuilder<tbPersonas> entity)
        {
            entity.HasKey(e => e.pers_Id);

            entity.Property(e => e.pers_Id).HasComment("Indica el identificador único de la persona.");

            entity.Property(e => e.pers_ApellidoMaterno)
                .HasMaxLength(50)
                .HasComment("Segundo apellido de la persona.");

            entity.Property(e => e.pers_ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Primer apellido dado a la persona.");

            entity.Property(e => e.pers_Calle)
                .HasMaxLength(150)
                .HasComment("Información sobre una direccion aproximada.");

            entity.Property(e => e.pers_Ciudad)
                .HasMaxLength(150)
                .HasComment("Información sobre una direccion aproximada.");

            entity.Property(e => e.pers_CodigoPostal)
                .HasMaxLength(150)
                .HasComment("Información sobre una direccion aproximada.");

            entity.Property(e => e.pers_CorreoElectronico)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Medio por el cual permite ponerse en contacto mediante mensaje electronico con la persona.");

            entity.Property(e => e.pers_EsActivo)
                .IsRequired()
                .HasDefaultValueSql("((1))")
                .HasComment("Indica el estado actual de la persona.");

            entity.Property(e => e.pers_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.pers_FechaNacimiento)
                .HasColumnType("date")
                .HasComment("Fecha en la que nacio la persona.");

            entity.Property(e => e.pers_FechaRegistra).HasColumnType("datetime");

            entity.Property(e => e.pers_Identidad)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasComment("Serie de digitos dado por el registro nacional para distingir únicamente a una persona.");

            entity.Property(e => e.pers_Pais)
                .HasMaxLength(150)
                .HasComment("Información sobre una direccion aproximada.");

            entity.Property(e => e.pers_PrimerNombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Primer nombre de la persona.");

            entity.Property(e => e.pers_Provincia)
                .HasMaxLength(150)
                .HasComment("Información sobre una direccion aproximada.");

            entity.Property(e => e.pers_SegundoNombre)
                .HasMaxLength(50)
                .HasComment("Segundo nombre de la persona.");

            entity.Property(e => e.pers_Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength(true)
                .HasComment("Indica el sexo de la persona.");

            entity.Property(e => e.pers_Telefono)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasComment("Almacena una serie de digitos de telefono.");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPersonas> entity);
    }
}
