// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.DataAccess.DbContextContainer.Configurations
{
    public partial class tbPrescripcionesConfiguration : IEntityTypeConfiguration<tbPrescripciones>
    {
        public void Configure(EntityTypeBuilder<tbPrescripciones> entity)
        {
            entity.HasKey(e => e.pres_Id)
                .HasName("PK_tbPrescripcion");

            entity.Property(e => e.pres_Descripcion).HasMaxLength(150);

            entity.Property(e => e.pres_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.pres_FechaRegistra).HasColumnType("datetime");

            entity.HasOne(d => d.cita)
                .WithMany(p => p.tbPrescripciones)
                .HasForeignKey(d => d.cita_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbPrescripcion_tbCita_cita_Id");

            entity.HasOne(d => d.medi)
                .WithMany(p => p.tbPrescripciones)
                .HasForeignKey(d => d.medi_Id)
                .HasConstraintName("FK_tbPrescripcion_tbMedicamentos_medi_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbPrescripciones> entity);
    }
}
