// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbTipoCitasConfiguration : IEntityTypeConfiguration<tbTipoCitas>
    {
        public void Configure(EntityTypeBuilder<tbTipoCitas> entity)
        {
            entity.HasKey(e => e.tici_Id)
                .HasName("PK_tbTipoCita");

            entity.Property(e => e.tici_Descripcion)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.tici_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.tici_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbTipoCitas> entity);
    }
}
