// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbTiposSangreConfiguration : IEntityTypeConfiguration<tbTiposSangre>
    {
        public void Configure(EntityTypeBuilder<tbTiposSangre> entity)
        {
            entity.HasKey(e => e.tipsan_Id);

            entity.Property(e => e.tipsan_Descripcion)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.tipsan_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.tipsan_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbTiposSangre> entity);
    }
}
