// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.Entities.DbContextContainer;
using PROMEDICAL.Entities.Entities;
using System;

namespace PROMEDICAL.Entities.DbContextContainer.Configurations
{
    public partial class tbTipoConsultasConfiguration : IEntityTypeConfiguration<tbTipoConsultas>
    {
        public void Configure(EntityTypeBuilder<tbTipoConsultas> entity)
        {
            entity.HasKey(e => e.tico_Id)
                .HasName("PK_tbTipoConsulta");

            entity.Property(e => e.tico_Id).ValueGeneratedNever();

            entity.Property(e => e.tico_Descripcion)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.tico_FechaModifica).HasColumnType("datetime");

            entity.Property(e => e.tico_FechaRegistra).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbTipoConsultas> entity);
    }
}
