// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class PacientesDto
    {
        /// <summary>
        /// Identificador único de la tabla pacientes.
        /// </summary>
        public int paci_Id { get; set; }
        /// <summary>
        /// Este es el ID de la persona que hace referencia al primary key de la tabla Personas.
        /// </summary>
        public int pers_Id { get; set; }
        public int? emps_Id { get; set; }
        /// <summary>
        /// Este es el ID del tipo de sangre que hace referencia al primary key de la tabla TiposSangre.
        /// </summary>
        public int tipsan_Id { get; set; }
        /// <summary>
        /// Información de la altura en metros del pasiente.
        /// </summary>
        [Column(TypeName = "decimal(3, 2)")]
        public decimal peci_altura { get; set; }
        /// <summary>
        /// Campo que contiene la información del peso en libras del paciente.
        /// </summary>
        public int peci_peso { get; set; }
        public bool paci_EsEliminado { get; set; }
        public int paci_UsuarioRegistra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime paci_FechaRegistra { get; set; }
        public int? paci_UsuarioModifica { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? paci_FechaModifica { get; set; }
    }
}
