// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class TipoCitasFindDto
    {
        public int tici_Id { get; set; }
        public string tici_Descripcion { get; set; }
    }
}
