// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class CargosSelectDto
    {
        public int carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
    }
}
