// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbCirugias
    {
        public int ciru_Id { get; set; }
        public string ciru_Descripcion { get; set; }
        public bool ciru_EsEliminado { get; set; }
        public int ciru_UsuarioRegistra { get; set; }
        public DateTime ciru_FechaRegistra { get; set; }
        public int? ciru_UsuarioModifica { get; set; }
        public DateTime? ciru_FechaModifica { get; set; }

        public virtual tbPacientes_tbCirugias tbPacientes_tbCirugias { get; set; }

        public object ToList()
        {
            throw new NotImplementedException();
        }
    }
}