// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbConsultorios
    {
        public tbConsultorios()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int cons_Id { get; set; }
        /// <summary>
        /// Informacion relevante de la ubicacion del consultorio.
        /// </summary>
        public string cons_Descripcion { get; set; }
        public bool cons_EsEliminado { get; set; }
        public int cons_UsuarioRegistra { get; set; }
        public DateTime cons_FechaRegistra { get; set; }
        public int? cons_UsuarioModifica { get; set; }
        public DateTime? cons_FechaModifica { get; set; }

        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}