// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbEmpresas
    {
        public tbEmpresas()
        {
            tbPacientes = new HashSet<tbPacientes>();
        }

        public int emps_Id { get; set; }
        public string emps_RTN { get; set; }
        public string emps_NombreComercial { get; set; }
        /// <summary>
        /// Medio por el cual permite ponerse en contacto mediante mensaje electronico con la persona.
        /// </summary>
        public string emps_CorreoElectronico { get; set; }
        /// <summary>
        /// Almacena una serie de digitos de telefono.
        /// </summary>
        public string emps_Telefono { get; set; }
        /// <summary>
        /// Información sobre una direccion aproximada.
        /// </summary>
        public string emps_Direccion { get; set; }
        /// <summary>
        /// Indica el estado actual de la persona.
        /// </summary>
        public bool? emps_EsActivo { get; set; }
        public bool emps_EsEliminado { get; set; }
        public int emps_UsuarioRegistra { get; set; }
        public DateTime emps_FechaRegistra { get; set; }
        public int? emps_UsuarioModifica { get; set; }
        public DateTime? emps_FechaModifica { get; set; }

        public virtual ICollection<tbPacientes> tbPacientes { get; set; }
    }
}