// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbCitas = new HashSet<tbCitas>();
        }

        public int empd_Id { get; set; }
        public int? pers_Id { get; set; }
        public int? carg_Id { get; set; }
        public int? espc_Id { get; set; }
        public int? cons_Id { get; set; }
        public int? jorn_Id { get; set; }
        public int? emps_Id { get; set; }
        public bool? empd_EsEliminado { get; set; }
        public int? empd_UsuarioRegistra { get; set; }
        public DateTime? empd_FechaRegistra { get; set; }
        public int? empd_UsuarioModifica { get; set; }
        public DateTime? empd_FechaModifica { get; set; }

        public virtual tbCargos carg { get; set; }
        public virtual tbConsultorios cons { get; set; }
        public virtual tbEmpresas emps { get; set; }
        public virtual tbEspecialidades espc { get; set; }
        public virtual tbJornadas jorn { get; set; }
        public virtual tbPersonas pers { get; set; }
        public virtual ICollection<tbCitas> tbCitas { get; set; }
    }
}