// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbEspecialidades
    {
        public tbEspecialidades()
        {
            tbCitas = new HashSet<tbCitas>();
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int espc_Id { get; set; }
        public string espc_Descripcion { get; set; }
        public bool espc_EsEliminado { get; set; }
        public int espc_UsuarioRegistra { get; set; }
        public DateTime espc_FechaRegistra { get; set; }
        public int? espc_UsuarioModifica { get; set; }
        public DateTime? espc_FechaModifica { get; set; }

        public virtual ICollection<tbCitas> tbCitas { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}