// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbFrecuenciasCardiacas
    {
        public int rica_Id { get; set; }
        /// <summary>
        /// Identificador del paciente
        /// </summary>
        public int paci_Id { get; set; }
        /// <summary>
        /// Frecuencia cardíaca alta del paciente
        /// </summary>
        public int rica_Alta { get; set; }
        /// <summary>
        /// Frecuencia cardíaca baja del paciente
        /// </summary>
        public int rica_Baja { get; set; }
        public bool rica_EsEliminado { get; set; }
        public int rica_UsuarioRegistra { get; set; }
        public DateTime rica_FechaRegistra { get; set; }
        public int? rica_UsuarioModifica { get; set; }
        public DateTime? rica_FechaModifica { get; set; }

        public virtual tbPacientes paci { get; set; }
    }
}