// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbMedicamentos
    {
        public tbMedicamentos()
        {
            tbPrescripciones = new HashSet<tbPrescripciones>();
        }

        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public decimal? medi_Precio { get; set; }
        public string medi_Descripcion { get; set; }
        public bool medi_EsEliminado { get; set; }
        public int medi_UsuarioRegistra { get; set; }
        public DateTime medi_FechaRegistra { get; set; }
        public int? medi_UsuarioModifica { get; set; }
        public DateTime? medi_FechaModifica { get; set; }

        public virtual ICollection<tbPrescripciones> tbPrescripciones { get; set; }
    }
}