// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbPacientes
    {
        public tbPacientes()
        {
            tbCitas = new HashSet<tbCitas>();
            tbFrecuenciasCardiacas = new HashSet<tbFrecuenciasCardiacas>();
            tbPacientes_tbAlergias = new HashSet<tbPacientes_tbAlergias>();
            tbPacientes_tbCirugias = new HashSet<tbPacientes_tbCirugias>();
            tbPesos = new HashSet<tbPesos>();
        }

        public int paci_Id { get; set; }
        public int? pers_Id { get; set; }
        public int? hist_Id { get; set; }
        public string tipoSangre { get; set; }
        public int? altura { get; set; }
        public int? peso { get; set; }
        public bool? paci_EsEliminado { get; set; }
        public int? paci_UsuarioRegistra { get; set; }
        public DateTime? paci_FechaRegistra { get; set; }
        public int? paci_UsuarioModifica { get; set; }
        public DateTime? paci_FechaModifica { get; set; }

        public virtual tbPersonas pers { get; set; }
        public virtual ICollection<tbCitas> tbCitas { get; set; }
        public virtual ICollection<tbFrecuenciasCardiacas> tbFrecuenciasCardiacas { get; set; }
        public virtual ICollection<tbPacientes_tbAlergias> tbPacientes_tbAlergias { get; set; }
        public virtual ICollection<tbPacientes_tbCirugias> tbPacientes_tbCirugias { get; set; }
        public virtual ICollection<tbPesos> tbPesos { get; set; }
    }
}