// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbPesos
    {
        public int peso_Id { get; set; }
        public int paci_Id { get; set; }
        public string peso_Descripcion { get; set; }
        public bool peso_EsEliminado { get; set; }
        public int peso_UsuarioRegistra { get; set; }
        public DateTime peso_FechaRegistra { get; set; }
        public int? peso_UsuarioModifica { get; set; }
        public DateTime? peso_FechaModifica { get; set; }
    }
}