// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROMEDICAL.Entities.Entities
{
    public partial class tbTipoCitas
    {
        public tbTipoCitas()
        {
            tbCitas = new HashSet<tbCitas>();
        }

        public int tici_Id { get; set; }
        public string tici_Descripcion { get; set; }
        public bool? tici_EsEliminado { get; set; }
        public int? tici_UsuarioRegistra { get; set; }
        public DateTime? tici_FechaRegistra { get; set; }
        public int? tici_UsuarioModifica { get; set; }
        public DateTime? tici_FechaModifica { get; set; }

        public virtual ICollection<tbCitas> tbCitas { get; set; }
    }
}