// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Medicamentos_SelectResult
    {
        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public string medi_Marca { get; set; }
        public string medi_Descripcion { get; set; }
    }
}
