// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Pacientes_DetailResult
    {
        public int paci_Id { get; set; }
        public string pers_Identidad { get; set; }
        public string pers_PrimerNombre { get; set; }
        public string pers_SegundoNombre { get; set; }
        public string pers_ApellidoPaterno { get; set; }
        public string pers_ApellidoMaterno { get; set; }
        public DateTime pers_FechaNacimiento { get; set; }
        public string pers_CorreoElectronico { get; set; }
        public string pers_Telefono { get; set; }
        public string pers_Calle { get; set; }
        public string pers_Ciudad { get; set; }
        public string pers_Provincia { get; set; }
        public string pers_CodigoPostal { get; set; }
        public string pers_Pais { get; set; }
        public string pers_Sexo { get; set; }
        public bool pers_EsActivo { get; set; }
        public bool pers_EsEliminado { get; set; }
        public int pers_UsuarioRegistra { get; set; }
        public DateTime pers_FechaRegistra { get; set; }
        public int? pers_UsuarioModifica { get; set; }
        public DateTime? pers_FechaModifica { get; set; }
        public int tipsan_Id { get; set; }
        public string peci_altura { get; set; }
        public int peci_peso { get; set; }
        public int paci_UsuarioRegistra { get; set; }
        public DateTime paci_FechaRegistra { get; set; }
        public int? paci_UsuarioModifica { get; set; }
        public DateTime? paci_FechaModifica { get; set; }
        public string emps_NombreComercial { get; set; }
        public string emps_RTN { get; set; }
        public string emps_CorreoElectronico { get; set; }
        public string emps_Telefono { get; set; }
        public string emps_Direccion { get; set; }
        public bool emps_EsActivo { get; set; }
        public bool emps_EsEliminado { get; set; }
        public int emps_UsuarioRegistra { get; set; }
        public DateTime emps_FechaRegistra { get; set; }
        public int? emps_UsuarioModifica { get; set; }
        public DateTime? emps_FechaModifica { get; set; }
    }
}
