// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Pesos_SelectResult
    {
        public int peso_Id { get; set; }
        public int? paci_Id { get; set; }
        public string peso_Descripcion { get; set; }
    }
}
