// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Empleados_SelectResult
    {
        public int empd_Id { get; set; }
        public string pers_Identidad { get; set; }
        public string pers_PrimerNombre { get; set; }
        public string pers_ApellidoPaterno { get; set; }
        public string carg_Descripcion { get; set; }
        public string cons_Descripcion { get; set; }
        public string jorn_Descripcion { get; set; }
    }
}
