// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Jornadas_DetailResult
    {
        public int jorn_Id { get; set; }
        public string jorn_Descripcion { get; set; }
        public int jorn_UsuarioRegistra { get; set; }
        public DateTime jorn_FechaRegistra { get; set; }
        public int? jorn_UsuarioModifica { get; set; }
        public DateTime? jorn_FechaModifica { get; set; }
    }
}
