// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Pacientes_SelectResult
    {
        public int paci_Id { get; set; }
        public string pers_Identidad { get; set; }
        public string paci_Nombres { get; set; }
        public decimal peci_altura { get; set; }
        public int peci_peso { get; set; }
        public string emps_NombreComercial { get; set; }
        public string emps_RTN { get; set; }
        public string emps_Telefono { get; set; }
    }
}
