// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Consultorios_FindResult
    {
        public int cons_Id { get; set; }
        public string cons_Descripcion { get; set; }
    }
}
