// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Cargos_FindResult
    {
        public int carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
        public int carg_UsuarioRegistra { get; set; }
        public DateTime carg_FechaRegistra { get; set; }
        public int? carg_UsuarioModifica { get; set; }
        public DateTime? carg_FechaModifica { get; set; }
    }
}
