// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_TipoCitas_DetailResult
    {
        public int tici_Id { get; set; }
        public string tici_Descripcion { get; set; }
        public int tici_UsuarioRegistra { get; set; }
        public DateTime tici_FechaRegistra { get; set; }
        public int? tici_UsuarioModifica { get; set; }
        public DateTime? tici_FechaModifica { get; set; }
    }
}
