// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Especialidades_DetailResult
    {
        public int espc_Id { get; set; }
        public string espc_Descripcion { get; set; }
        public int espc_UsuarioRegistra { get; set; }
        public DateTime espc_FechaRegistra { get; set; }
        public int? espc_UsuarioModifica { get; set; }
        public DateTime? espc_FechaModifica { get; set; }
    }
}
