// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Empresas_SelectResult
    {
        public int emps_Id { get; set; }
        public string emps_RTN { get; set; }
        public string emps_NombreComercial { get; set; }
        public string emps_CorreoElectronico { get; set; }
        public string emps_Telefono { get; set; }
        public string emps_Direccion { get; set; }
        public bool emps_EsActivo { get; set; }
    }
}
