// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Medicamentos_DetailResult
    {
        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public string medi_Marca { get; set; }
        public string medi_Descripcion { get; set; }
        public int medi_UsuarioRegistra { get; set; }
        public DateTime medi_FechaRegistra { get; set; }
        public int? medi_UsuarioModifica { get; set; }
        public DateTime? medi_FechaModifica { get; set; }
    }
}
