// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Pesos_DetailResult
    {
        public int peso_Id { get; set; }
        public int paci_Id { get; set; }
        public string peso_Descripcion { get; set; }
        public int peso_UsuarioRegistra { get; set; }
        public DateTime peso_FechaRegistra { get; set; }
        public int? peso_UsuarioModifica { get; set; }
        public DateTime? peso_FechaModifica { get; set; }
    }
}
