// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Entities.Entities
{
    public partial class UDP_Citas_SelectResult
    {
        public int cita_Id { get; set; }
        public int paci_Id { get; set; }
        public string paci_PrimerNombre { get; set; }
        public string paci_ApellidoPaterno { get; set; }
        public int empd_Id { get; set; }
        public string empd_PrimerNombre { get; set; }
        public string empd_ApellidoPaterno { get; set; }
        public int tici_Id { get; set; }
        public string tici_Descripcion { get; set; }
        public DateTime cita_FechaCita { get; set; }
        public int cita_UsuarioRegistra { get; set; }
        public DateTime cita_FechaRegistra { get; set; }
        public int? cita_UsuarioModifica { get; set; }
        public DateTime? cita_FechaModifica { get; set; }
    }
}
