// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROMEDICAL.Business.Dto
{
    public partial class EmpresasDto
    {
        public int emps_Id { get; set; }
        public string emps_RTN { get; set; }
        public string emps_NombreComercial { get; set; }
        public string emps_CorreoElectronico { get; set; }
        public string emps_Telefono { get; set; }
        public string emps_Direccion { get; set; }
        [Required]
        public bool? emps_EsActivo { get; set; }
        public bool emps_EsEliminado { get; set; }
        public int emps_UsuarioRegistra { get; set; }
        public DateTime emps_FechaRegistra { get; set; }
        public int? emps_UsuarioModifica { get; set; }
        public DateTime? emps_FechaModifica { get; set; }
    }
}
