<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Especific\NewFolder\**" />
    <EmbeddedResource Remove="Interfaces\Especific\NewFolder\**" />
    <None Remove="Interfaces\Especific\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PROMEDICAL.DataAccess\PROMEDICAL.DataAccess.csproj" />
    <ProjectReference Include="..\PROMEDICAL.Entities\PROMEDICAL.Entities.csproj" />
  </ItemGroup>

</Project>
