// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROMEDICAL.Business.Dto
{
    public partial class PrescripcionesDetailDto
    {
        public int pres_Id { get; set; }
        public int cita_Id { get; set; }
        public int medi_Id { get; set; }
        public string pres_Descripcion { get; set; }
        public int pres_UsuarioRegistra { get; set; }
        public DateTime pres_FechaRegistra { get; set; }
        public int? pres_UsuarioModifica { get; set; }
        public DateTime? pres_FechaModifica { get; set; }
    }
}
