// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PROMEDICAL.DataAccess.DbContextContainer.Configurations;
using System;
using PROMEDICAL.Entities.Entities;
#nullable disable

#nullable disable

namespace PROMEDICAL.DataAccess.DbContextContainer
{
    public partial class MedicalSystemContext : DbContext
    {
        public MedicalSystemContext()
        {
        }

        public MedicalSystemContext(DbContextOptions<MedicalSystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbAlergias> tbAlergias { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCirugias> tbCirugias { get; set; }
        public virtual DbSet<tbCitas> tbCitas { get; set; }
        public virtual DbSet<tbConsultorios> tbConsultorios { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEmpresas> tbEmpresas { get; set; }
        public virtual DbSet<tbEspecialidades> tbEspecialidades { get; set; }
        public virtual DbSet<tbFrecuenciasCardiacas> tbFrecuenciasCardiacas { get; set; }
        public virtual DbSet<tbJornadas> tbJornadas { get; set; }
        public virtual DbSet<tbMedicamentos> tbMedicamentos { get; set; }
        public virtual DbSet<tbPacientes> tbPacientes { get; set; }
        public virtual DbSet<tbPacientes_tbAlergias> tbPacientes_tbAlergias { get; set; }
        public virtual DbSet<tbPacientes_tbCirugias> tbPacientes_tbCirugias { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbPesos> tbPesos { get; set; }
        public virtual DbSet<tbPrescripciones> tbPrescripciones { get; set; }
        public virtual DbSet<tbTipoCitas> tbTipoCitas { get; set; }
        public virtual DbSet<tbTipoConsultas> tbTipoConsultas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.tbAlergiasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbCargosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbCirugiasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbCitasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbConsultoriosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbEmpleadosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbEmpresasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbEspecialidadesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbFrecuenciasCardiacasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbJornadasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbMedicamentosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbPacientesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbPacientes_tbAlergiasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbPacientes_tbCirugiasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbPersonasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbPesosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbPrescripcionesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbTipoCitasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.tbTipoConsultasConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
